### ISSUE TITLE
Who is @KodekPL

### ISSUE THREAD

**Issue by James-Parsons** [catoja1107/Template#2]
It seems that @KodekPL did all the work. Who is that?

**Comment by catoja1107** [comment]
Wtf i have no idea but i do know that i pushed it to the repository, but
its showing under his name.

**Comment by James-Parsons** [comment]
In the git command line, what does it say when you type in: `git config user.name`?

**Comment by catoja1107** [comment]
BuildTools

**Comment by James-Parsons** [comment]
what about `git config user.email`?

**Comment by catoja1107** [comment]
unconfigured@null.spigotmc.org

**Comment by catoja1107** [comment]
Changed it

**Comment by James-Parsons** [comment]
lol what even:P

**Comment by catoja1107** [comment]
ik

**Comment by catoja1107** [comment]
![40443511](https://cloud.githubusercontent.com/assets/9062530/9373568/e3ee5d34-46b9-11e5-83f0-602c282ab449.jpg)

**Comment by catoja1107** [comment]
OK, I'm closing the Issue.
